# ===== Oracle DB 설정 =====
db.url=jdbc:oracle:thin:@localhost:1521:xe
db.username=hr
db.password=hr

# ===== Google OAuth2 =====
google.client.id=612135648919-pou6ode0nl15s1vtfsfeqpsv9qogg4g7.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8088/Mapple_Spring/member/oauth/google/callback

# ===== Kakao OAuth2 =====
kakao.client.id=56a386334472d684fd864e7aa382b567
kakao.client.secret=syyRzCqJDQ7T6FSiJ85J7WDxAtRGsrwW
kakao.redirect.uri=http://localhost:8088/Mapple_Spring/member/oauth/kakao/callback

# ===== 넥슨 OPEN API =====
nexon.api.key=test_fb4507d1917796fae08b7e3fa5d087ca2f2589426620a625990a4b48c9fde899efe8d04e6d233bd35cf2fabdeb93fb0d
nexon.api.base-url=https://open.api.nexon.com
